### CONFIGURATION VARIABLES ###
# Uncomment and set variables if you wish to change the default ones

# Number of threads used
# threads = 2 # Number of threads for the application

# Folder to look for applications
# downloads_folder = "downloads" # Folder for APK files

# Folder where the source code will be extracted
# dist_folder = "dist"

# Folder where results will be generated
# results_folder = "results"

# Dex2Jar folder
# dex2jar_folder = "/usr/share/super-analyzer/vendor/dex2jar-2.1-SNAPSHOT"

# JD-cmd JAR file
# jd_cmd_file = "/usr/share/super-analyzer/vendor/jd-cmd.jar"

# Templates folder
# templates_folder = "/usr/share/super-analyzer/templates"

# Results template used
# template = "super"

# Vulnerability rules JSON
# rules_json = "/etc/super-analyzer/rules.json"

# Generates HTML report
# html_report = true

# Generates JSON report
# json_report = false

### PERMISSIONS ###
# Add or remove permissions if you wish to change them. The format is the following:
#[[permissions]]
#name = "unknown" # Unknown permissions
#criticality = "low"
#description = "Even if the application can create its own permissions, it's discouraged, since it can lead to missunderstanding between developers."
